### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by likwidoxigen** [CodingGarden/stream-overlay-alerts#3]
Just realized there's no license on this repo. I know that there's some provenance things between you and @MurdocTurner so I'm not sure which repo makes the most sense to ask this on, but is there a plan to apply a license or are all right's being reserved intentionally?

**Comment by w3cj** [comment]
Added the MIT license: https://github.com/CodingGarden/stream-overlay-alerts/blob/master/LICENSE
